// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNrPj9uz0_TQ5KsCgoYMnpkvmcMsYYrM',
    appId: '1:798104857873:web:858a2d1931a7141692b0b0',
    messagingSenderId: '798104857873',
    projectId: 'proyectointegrado1-376f7',
    authDomain: 'proyectointegrado1-376f7.firebaseapp.com',
    storageBucket: 'proyectointegrado1-376f7.firebasestorage.app',
    measurementId: 'G-KL8XHP2LVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQAttLrnZ_VltMIH5bPqJvCYG-oHucyPA',
    appId: '1:798104857873:android:5c82143e3b23fc5b92b0b0',
    messagingSenderId: '798104857873',
    projectId: 'proyectointegrado1-376f7',
    storageBucket: 'proyectointegrado1-376f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBij5iF_18cq3qnucVwMhfRfFFtr6g5djQ',
    appId: '1:798104857873:ios:c5e6fae9ffe0f80992b0b0',
    messagingSenderId: '798104857873',
    projectId: 'proyectointegrado1-376f7',
    storageBucket: 'proyectointegrado1-376f7.firebasestorage.app',
    iosBundleId: 'com.example.proyectointegrado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBij5iF_18cq3qnucVwMhfRfFFtr6g5djQ',
    appId: '1:798104857873:ios:c5e6fae9ffe0f80992b0b0',
    messagingSenderId: '798104857873',
    projectId: 'proyectointegrado1-376f7',
    storageBucket: 'proyectointegrado1-376f7.firebasestorage.app',
    iosBundleId: 'com.example.proyectointegrado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdNrPj9uz0_TQ5KsCgoYMnpkvmcMsYYrM',
    appId: '1:798104857873:web:853f997608726c4c92b0b0',
    messagingSenderId: '798104857873',
    projectId: 'proyectointegrado1-376f7',
    authDomain: 'proyectointegrado1-376f7.firebaseapp.com',
    storageBucket: 'proyectointegrado1-376f7.firebasestorage.app',
    measurementId: 'G-63S34LFRF8',
  );
}
